name: test
on: 
    - push
    - pull_request

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: Denocord/deno-action@master
              with:
                args: '["test", "-A", "test/"]'